#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
CSV to SQL Converter untuk Badransari_Export.csv
Mengkonversi CSV ke SQL INSERT statements yang siap dijalankan di MySQL/PhpMyAdmin
"""

import csv
import sys
import os
from pathlib import Path

def detect_delimiter(file_path, sample_lines=5):
    """Deteksi delimiter CSV (koma atau semicolon)"""
    with open(file_path, 'r', encoding='utf-8-sig') as f:
        sample = f.read(1024)
    
    comma_count = sample.count(',')
    semicolon_count = sample.count(';')
    
    return ';' if semicolon_count > comma_count else ','

def csv_to_sql(csv_file, output_file, table_name='residents'):
    """
    Konversi CSV ke SQL INSERT statements
    
    Args:
        csv_file: Path ke file CSV
        output_file: Path untuk output SQL
        table_name: Nama tabel di database
    """
    
    print(f"📂 Membaca file: {csv_file}")
    
    # Deteksi delimiter
    delimiter = detect_delimiter(csv_file)
    print(f"🔍 Delimiter terdeteksi: '{delimiter}'")
    
    sql_statements = []
    error_rows = []
    success_count = 0
    
    try:
        with open(csv_file, 'r', encoding='utf-8-sig', errors='replace') as f:
            reader = csv.DictReader(f, delimiter=delimiter)
            
            if reader.fieldnames is None:
                print("❌ Error: File CSV tidak memiliki header")
                return False
            
            print(f"✅ Kolom ditemukan: {', '.join(reader.fieldnames)}")
            
            for row_num, row in enumerate(reader, start=2):
                try:
                    # Bersihkan data
                    cleaned_row = {}
                    for key, value in row.items():
                        if key:
                            key = key.strip()
                            value = value.strip() if value else ''
                            cleaned_row[key] = value
                    
                    if not cleaned_row or all(v == '' for v in cleaned_row.values()):
                        continue
                    
                    # Build INSERT statement
                    columns = []
                    values = []
                    
                    for col, val in cleaned_row.items():
                        if val:  # Hanya jika ada value
                            columns.append(f"`{col}`")
                            # Escape single quotes
                            val = val.replace("'", "''")
                            values.append(f"'{val}'")
                    
                    if columns:
                        insert_stmt = f"INSERT INTO `{table_name}` ({', '.join(columns)}) VALUES ({', '.join(values)});"
                        sql_statements.append(insert_stmt)
                        success_count += 1
                
                except Exception as e:
                    error_rows.append((row_num, str(e)))
                    print(f"⚠️  Baris {row_num} error: {e}")
        
        # Write ke file SQL
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write("-- ===================================\n")
            f.write("-- SQL Import untuk Badransari_Export.csv\n")
            f.write("-- Generated by csv_to_sql_converter.py\n")
            f.write("-- ===================================\n\n")
            f.write("SET NAMES utf8mb4;\n")
            f.write("SET CHARACTER SET utf8mb4;\n\n")
            f.write(f"-- Jangan lupa: ALTER TABLE `{table_name}` DISABLE KEYS;\n\n")
            
            for stmt in sql_statements:
                f.write(stmt + "\n")
            
            f.write(f"\n-- ALTER TABLE `{table_name}` ENABLE KEYS;\n")
            f.write(f"\n-- Total: {success_count} records imported\n")
        
        # Print summary
        print("\n" + "="*50)
        print(f"✅ Konversi berhasil!")
        print(f"📊 Total records: {success_count}")
        print(f"⚠️  Error rows: {len(error_rows)}")
        print(f"💾 Output file: {output_file}")
        print("="*50 + "\n")
        
        if error_rows:
            print("Error details:")
            for row_num, error in error_rows[:10]:
                print(f"  Baris {row_num}: {error}")
        
        return True
        
    except Exception as e:
        print(f"❌ Error: {e}")
        return False

def main():
    """Main function"""
    
    # Path konfigurasi
    csv_path = "database/seeders/Badransari_Export.csv"
    sql_path = "database/sql/Badransari_Import.sql"
    
    # Cek apakah file CSV ada
    if not os.path.exists(csv_path):
        print(f"❌ File tidak ditemukan: {csv_path}")
        print("\nTaruh file CSV di: database/seeders/Badransari_Export.csv")
        return
    
    # Buat direktori output jika belum ada
    Path(os.path.dirname(sql_path)).mkdir(parents=True, exist_ok=True)
    
    # Konversi
    print("🚀 CONVERTER CSV ke SQL - Badransari\n")
    
    # Deteksi table name dari header CSV
    delimiter = detect_delimiter(csv_path)
    with open(csv_path, 'r', encoding='utf-8-sig') as f:
        reader = csv.DictReader(f, delimiter=delimiter)
        header = reader.fieldnames
    
    # Tentukan tabel berdasarkan kolom
    if header and ('nik' in [h.lower() for h in header] or 'no_identitas' in [h.lower() for h in header]):
        table_name = 'residents'
    else:
        table_name = 'residents'
    
    print(f"📋 Target table: {table_name}\n")
    
    # Run converter
    success = csv_to_sql(csv_path, sql_path, table_name)
    
    if success:
        print("\n📌 LANGKAH SELANJUTNYA:")
        print("="*50)
        print("1. Buka PhpMyAdmin di Domainesia")
        print("2. Pilih database 'badransa_webdesa'")
        print("3. Klik tab 'Import'")
        print("4. Upload file: database/sql/Badransari_Import.sql")
        print("5. Klik 'Go'")
        print("="*50)

if __name__ == '__main__':
    main()
